May 22 22:41:07 (1400787667) python[12054]: /etc/dante.conf: error on line 24, near '/var/log/s': fopen(/var/log/socks/danted.log): No such file or directory (errno = 2)
May 22 23:51:44 (1400791904) python[16933]: dante/client v1.1.19 running
May 22 23:51:44 (1400791904) python[16933]: socketoptdup(): setsockopt(0, 32): Invalid argument (errno = 22)
May 22 23:51:44 (1400791904) python[16933]: socketoptdup(): setsockopt(0, 33): Invalid argument (errno = 22)
May 22 23:51:44 (1400791904) python[16933]: socketoptdup(): setsockopt(0, 32): Invalid argument (errno = 22)
May 22 23:51:44 (1400791904) python[16933]: socketoptdup(): setsockopt(0, 33): Invalid argument (errno = 22)
May 22 23:51:44 (1400791904) python[16934]: run_connectchild(): connect failed: Connection refused (errno = 111)
May 22 23:51:44 (1400791904) python[16934]: run_connectchild(): getpeername(control): Transport endpoint is not connected (errno = 107)
May 22 23:51:44 (1400791904) python[16933]: sigchld(): getpeername(s): Transport endpoint is not connected (errno = 107)
May 22 23:51:44 (1400791904) python[16934]: run_connectchild(): recvmsgn(): mother closed
May 22 23:59:49 (1400792389) python[16950]: dante/client v1.1.19 running
May 22 23:59:49 (1400792389) python[16950]: socketoptdup(): setsockopt(0, 32): Invalid argument (errno = 22)
May 22 23:59:49 (1400792389) python[16950]: socketoptdup(): setsockopt(0, 33): Invalid argument (errno = 22)
May 22 23:59:49 (1400792389) python[16950]: socketoptdup(): setsockopt(0, 32): Invalid argument (errno = 22)
May 22 23:59:49 (1400792389) python[16950]: socketoptdup(): setsockopt(0, 33): Invalid argument (errno = 22)
May 22 23:59:49 (1400792389) python[16951]: run_connectchild(): connect failed: Connection refused (errno = 111)
May 22 23:59:49 (1400792389) python[16951]: run_connectchild(): getpeername(control): Transport endpoint is not connected (errno = 107)
May 22 23:59:49 (1400792389) python[16950]: sigchld(): getpeername(s): Transport endpoint is not connected (errno = 107)
May 22 23:59:49 (1400792389) python[16951]: run_connectchild(): recvmsgn(): mother closed
